language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: I0qRmufLwnc/LeXe3tY+Dzik1srmy4st6ZN0DcsrEpd8gxHLfypRPFORd2xRLWI62fcZBnePbX97KWHTAt/lo3oqdL0uLHOuGGwVMrkwowHh1kPf4lngf/xCTtTXz7AknJV1KqKgInn2Ah3hlaL7MMjSvukNHSpTwBAkRkcxIg7BjFWc6ohKusXmRY4rM0J8+bACyHwb1SlVVuGX+M2sOPaNdoXEbOZwJdWhJqBi0AQ+y6+QFHGdNNIsI5Irsaqc6Hw6GyfUhGG5N6rdCFo/cY9JF5rPvSAVzOrwJN0tLKLn6lkrJf087MYcKBcA4tDgUVM82c3Jn1N3OB4lOuFTiZrHAC8D9e5acssrY6ltyqBLRO4vYSGV1/4SMbFezkNQ7n8XZVoYru+FNoB53ebUx5H4KxbgiEx/HNZ9N9jetQqlONSMQO34y2oGBUl2WDdVVw/fbbLD0FGoCLnN3onDam/L/8PiIwxLMK0NRW46wSJAqsmCDiNjA7PJL20JqZk1hEjzg4BuzpqFfmBCHsRChUmM5gV9vk2n8EJQbuVevUAqxQMLdFxk96PKp6SH7vXvuReR+KLWU6xCXYkDD2hXi2rUMd78VB2VlISV1pMUI9L4CtYpaS0nuR968MD8+uoJ4LCtNI8zNrwA8w6vnj/4La9yI7HGqP3vzKuF7ltoN80=
  app: tranquil-beach-39479
  on:
    repo: BakerStudio/node-shopping-list-integration-tests
